APPLICATION = ea_jelling

USEMODULE += llstats

include $(CURDIR)/../../Makefile.exp.include
include $(CURDIR)/../Makefile.ea.include

USEMODULE += nimble_jelling
USEMODULE += ztimer_usec

include $(RIOTBASE)/Makefile.include
