APPLICATION = ea_statconn

USEMODULE += llstats

include $(CURDIR)/../../Makefile.exp.include
include $(CURDIR)/../Makefile.ea.include

USEMODULE += bledump
USEMODULE += nimble_statconn

include $(RIOTBASE)/Makefile.include
